GET http://localhost:8899/api/like
###
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "someone009@ggg.mail",
 "password" : "123456"
}
###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#   "identity" : "123456789",
 "identity" : "someone123@ggg.mail",
 "firstName" : "Weekended",
 "lastName" : "CodeCamp",
 "password" : "123456",
 "confirmPassword" : "123456"
}


###
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
   "message": "sample"
}
###
