GET http://localhost:8899/api/like
###
POST http://localhost:8899/api/auth/login HTTP/1.1
content-type: application/json

{
 "identity" : "andy@cc20.th",
 "password" : "a1234"
}
###

# Register api
POST http://localhost:8899/api/auth/register HTTP/1.1
content-type: application/json

{
#   "identity" : "12345678901",
 "identity" : "someone007@ggg.mail",
 "firstName" : "Weekend",
 "lastName" : "CodeCamp",
 "password" : "123456",
 "confirmPassword" : "12346"
}


###
POST http://localhost:8899/api/post HTTP/1.1
content-type: application/json

{
   "message": "sample"
}
###
